// frontend/src/utils/types.ts

import { ethers } from "ethers";

// Interface for the raw proof generated by snarkjs
export interface RawProof {
    pi_a: [string, string, string];
    pi_b: [[string, string], [string, string], [string, string]];
    pi_c: [string, string, string];
}

// Interface for the formatted proof expected by the contract
export interface FormattedProof {
    pi_a: [string, string];
    pi_b: [[string, string], [string, string]];
    pi_c: [string, string];
}

// Interface for the contract artifacts generated by the deployment script
export interface ContractArtifacts {
    address: string;
    abi: any[];
}

// Type for the callback function used in the event listener
export type PetStateUpdateCallback = (pairId: string, newState: number, timestamp: number) => void;
